N_horizon: 40
weights:
  origin: 200.0
  normal_alignment: 50.0
  x_alignment: 300.0
  fixed_x: 200.0
  fixed_vy: 100.0
lqr_terminal:
  P:
    type: full
    values:
    - - 243052.67029519114
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1060.829018023897
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 226899.79223259154
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 864.9939836434803
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 1101270.3187225857
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 2125.6677409024437
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 165750.358915187
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 221.63494531262415
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 187787.68737889826
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 436.53037758571156
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 152882.65647899968
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 98.73069093322502
    - - 1060.829018023897
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 9.518133158923186
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 864.9939836434803
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 7.634732444102561
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 2125.6677409024437
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 6.581049542252257
      - 0.0
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 221.63494531262415
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 2.1957160580151656
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 436.53037758571156
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 3.8762078276395076
      - 0.0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 98.73069093322502
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1.333852399303875
  alpha: 4010904.685964217
