robot:
  name: ur5
  dof: 6
  q_min: [-6.283, -6.283, -3.142, -6.283, -6.283, -6.283]
  q_max: [ 6.283,  6.283,  3.142,  6.283,  6.283,  6.283]
  dq_min: [-3.142, -3.142, -3.142, -3.142, -3.142, -3.142]
  dq_max: [ 3.142,  3.142,  3.142,  3.142,  3.142,  3.142]
  wcv: [228.9, 262.09, 517.3, 747.44, 429.9, 1547.76]